name: 03 - workflow - runners
on: workflow_dispatch

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
    - name: Show OS
      run: |
        echo "Runner OS: $RUNNER_OS"
        echo "Event type: ${{github.event_type}}"
  windows-echo:
    if: github.event.base_ref == 'refs/heads/main' || github.ref == 'refs/heads/main'
    needs: ubuntu-echo
    runs-on: windows-latest
    steps:
    -  name: Show OS
       shell: bash
       run: |
         echo "This is showing runner host where it is running"
         echo "Runner OS: $RUNNER_OS"
