name: 03 - workflow - runners
on: push
jobs:
  name: ubuntu-echo
  runs_on: ubuntu-latest
  steps:
    - name: Show OS
      run: |
        echo: "This job is running on ubuntu runner"
        echo: "Runner os: $RUNNER_OS"

